---
parser: '@typescript-eslint/parser'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - airbnb-base
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  node: true
  jest: true
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  semi:
    - error
    - never
  no-console: off
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  '@typescript-eslint/explicit-function-return-type': off
settings:
  import/resolver:
    node:
      extensions:
        - '.ts'
